packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/legacy/*'

overrides:
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  prismjs: 1.30.0
  postcss: 8.5.10
