// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: Button
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-primary-container-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-primary-container-hover": "light-dark(rgb(19 84 174), rgb(48 125 232))",
        "button-primary-container-active": "light-dark(rgb(13 77 165), rgb(117 174 240))",
        "button-primary-container-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-secondary-container-idle": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-secondary-container-hover": "light-dark(rgb(238 242 247), rgb(0 32 77))",
        "button-secondary-container-active": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-secondary-container-disabled": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-destructive-container-idle": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "button-destructive-container-hover": "light-dark(rgb(195 34 34), rgb(244 154 154))",
        "button-destructive-container-active": "light-dark(rgb(173 31 31), rgb(248 195 195))",
        "button-destructive-container-disabled": "light-dark(rgb(253 237 237), rgb(108 19 19))",
        "button-inverted-container-idle": "light-dark(rgb(11 66 142), rgb(190 215 244))",
        "button-inverted-container-hover": "light-dark(rgb(13 77 165), rgb(117 174 240))",
        "button-inverted-container-active": "light-dark(rgb(19 84 174), rgb(48 125 232))",
        "button-inverted-container-disabled": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "button-ai-container-idle": "linear-gradient(180deg, rgb(56 73 224) 20%, rgb(252 45 241) 100%)",
        "button-ai-container-hover": "linear-gradient(180deg, rgb(51 66 195) 20%, rgb(182 33 174) 100%)",
        "button-ai-container-active": "linear-gradient(180deg, rgb(43 54 155) 20%, rgb(118 21 113) 100%)",
        "button-ai-container-disabled": "linear-gradient(180deg, rgb(223 226 255) 20%, rgb(255 218 253) 100%)"
      },
      "textColor": {
        "button-primary-label-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-primary-label-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-primary-label-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-primary-label-disabled": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-secondary-label-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-secondary-label-hover": "light-dark(rgb(19 84 174), rgb(48 125 232))",
        "button-secondary-label-active": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "button-secondary-label-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-ghost-label-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-ghost-label-hover": "light-dark(rgb(19 84 174), rgb(48 125 232))",
        "button-ghost-label-active": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "button-ghost-label-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-destructive-label-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-destructive-label-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-destructive-label-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-destructive-label-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(0 0 0 / 0.302))",
        "button-inverted-label-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-inverted-label-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-inverted-label-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-inverted-label-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(0 0 0 / 0.302))",
        "button-ai-label-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-ai-label-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-ai-label-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-ai-label-disabled": "light-dark(rgb(255 255 255), rgb(0 0 0))"
      },
      "borderColor": {
        "button-secondary-container-border-color-idle": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-secondary-container-border-color-hover": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-secondary-container-border-color-active": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-secondary-container-border-color-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-inverted-container-border-color-idle": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-inverted-container-border-color-hover": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-inverted-container-border-color-active": "light-dark(rgb(0 0 0 / 0), rgb(0 0 0 / 0))",
        "button-inverted-container-border-color-disabled": "light-dark(rgb(255 255 255 / 0.102), rgb(0 0 0 / 0.102))"
      },
      "fill": {
        "button-primary-icon-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-primary-icon-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-primary-icon-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-primary-icon-disabled": "light-dark(rgb(255 255 255 / 0.898), rgb(0 0 0 / 0.898))",
        "button-secondary-icon-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-secondary-icon-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-secondary-icon-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-secondary-icon-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-ghost-icon-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-ghost-icon-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-ghost-icon-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-ghost-icon-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-destructive-icon-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-destructive-icon-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-destructive-icon-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-destructive-icon-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(0 0 0 / 0.302))",
        "button-inverted-icon-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-inverted-icon-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-inverted-icon-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-inverted-icon-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(0 0 0 / 0.302))",
        "button-ai-icon-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-ai-icon-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-ai-icon-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "button-ai-icon-disabled": "light-dark(rgb(255 255 255 / 0.898), rgb(0 0 0 / 0.898))"
      },
      "fontFamily": {
        "button-global-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "button-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "button-global-container-gap": "8px",
        "button-global-container-height": "32px",
        "button-global-container-padding-y": "8px",
        "button-global-icon-size": "16px",
        "button-primary-container-padding-x": "12px",
        "button-primary-container-width-min": "64px",
        "button-secondary-container-border-width": "1px",
        "button-secondary-container-padding-x": "12px",
        "button-secondary-container-width-min": "64px",
        "button-ghost-container-padding-x": "0px",
        "button-destructive-container-padding-x": "12px",
        "button-destructive-container-width-min": "64px",
        "button-inverted-container-border-width": "1px",
        "button-inverted-container-padding-x": "12px",
        "button-inverted-container-width-min": "64px",
        "button-ai-container-padding-x": "12px",
        "button-ai-container-width-min": "64px"
      },
      "borderRadius": {
        "button-global-container-border-radius": "4px"
      }
    },
  },
};
