// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: Chip
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "chip-global-box-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "chip-global-box-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "chip-global-box-idle": "light-dark(rgb(248 250 252), rgb(24 25 27))"
      },
      "textColor": {
        "chip-operational-label": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "chip-removable-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "chip-selectable-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "chip-global-border-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "chip-global-border-hover": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "chip-global-border-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "chip-global-icon": "light-dark(rgb(23 99 207), rgb(81 157 246))"
      },
      "fontFamily": {
        "chip-operational-label-text-style": "Inter, system-ui, sans-serif",
        "chip-removable-label-text-style": "Inter, system-ui, sans-serif",
        "chip-selectable-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "chip-operational-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "chip-removable-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "chip-selectable-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "chip-global-border-width": "1px",
        "chip-global-box-gap": "4px",
        "chip-global-box-height": "24px",
        "chip-global-box-margin-y": "4px",
        "chip-global-box-padding-x": "8px",
        "chip-global-box-width-min": "48px",
        "chip-global-icon-size": "16px"
      },
      "borderRadius": {
        "chip-global-border-radius": "12px"
      }
    },
  },
};
