// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep-sky-itkontoret • component: branding
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {},
  },
};
