// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: ButtonIcon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-icon-global-container-active": "light-dark(rgb(226 235 245), rgb(48 50 54))",
        "button-icon-global-container-disabled": "light-dark(transparent, transparent)",
        "button-icon-global-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "button-icon-global-container-idle": "light-dark(transparent, transparent)"
      },
      "borderColor": {
        "button-icon-secondary-container-border-color-active": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "button-icon-secondary-container-border-color-disabled": "light-dark(rgb(214 228 245), rgb(38 70 115))",
        "button-icon-secondary-container-border-color-hover": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "button-icon-secondary-container-border-color-idle": "light-dark(rgb(214 228 245), rgb(38 70 115))"
      },
      "fill": {
        "button-icon-global-icon-active": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "button-icon-global-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-icon-global-icon-hover": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "button-icon-global-icon-idle": "light-dark(rgb(23 99 207), rgb(81 157 246))"
      },
      "spacing": {
        "button-icon-global-container-height": "32px",
        "button-icon-global-container-padding-x": "4px",
        "button-icon-global-container-padding-y": "4px",
        "button-icon-global-container-width": "32px",
        "button-icon-global-icon-size": "16px",
        "button-icon-secondary-container-border-width": "1px"
      },
      "borderRadius": {
        "button-icon-global-container-border-radius": "4px"
      }
    },
  },
};
