// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: Resizable
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "borderColor": {
        "resizable-border-active": "light-dark(rgb(23 99 207), rgb(81 157 246))",
        "resizable-border-hover": "light-dark(rgb(23 99 207), rgb(81 157 246))"
      },
      "spacing": {
        "resizable-border-width": "1px"
      }
    },
  },
};
