// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: ButtonIcon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-icon-global-container-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "button-icon-global-container-disabled": "light-dark(transparent, transparent)",
        "button-icon-global-container-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "button-icon-global-container-idle": "light-dark(transparent, transparent)"
      },
      "borderColor": {
        "button-icon-secondary-container-border-color-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "button-icon-secondary-container-border-color-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "button-icon-secondary-container-border-color-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "button-icon-secondary-container-border-color-idle": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fill": {
        "button-icon-global-icon-active": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-icon-global-icon-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "button-icon-global-icon-hover": "light-dark(rgb(73 76 80), rgb(201 204 207))",
        "button-icon-global-icon-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "spacing": {
        "button-icon-global-container-height": "32px",
        "button-icon-global-container-padding-x": "4px",
        "button-icon-global-container-padding-y": "4px",
        "button-icon-global-container-width": "32px",
        "button-icon-global-icon-size": "16px",
        "button-icon-secondary-container-border-width": "1px"
      },
      "borderRadius": {
        "button-icon-global-container-border-radius": "4px"
      }
    },
  },
};
