// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: Link
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "link-inverse-text-active": "light-dark(rgb(190 215 244), rgb(41 81 122))",
        "link-inverse-text-hover": "light-dark(rgb(190 215 244), rgb(41 81 122))",
        "link-inverse-text-idle": "light-dark(rgb(190 215 244), rgb(41 81 122))",
        "link-normal-text-active": "light-dark(rgb(48 50 54), rgb(228 229 231))",
        "link-normal-text-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "link-normal-text-hover": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "link-normal-text-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "fill": {
        "link-inverse-external-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "link-inverse-external-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "link-inverse-external-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "link-normal-external-icon-active": "light-dark(rgb(48 50 54), rgb(228 229 231))",
        "link-normal-external-icon-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "link-normal-external-icon-hover": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "link-normal-external-icon-idle": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "fontFamily": {
        "link-global-text-style-active": "Inter, system-ui, sans-serif",
        "link-global-text-style-disabled": "Inter, system-ui, sans-serif",
        "link-global-text-style-hover": "Inter, system-ui, sans-serif",
        "link-global-text-style-idle": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "link-global-text-style-active": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-global-text-style-disabled": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-global-text-style-hover": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-global-text-style-idle": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "link-global-container-gap": "4px",
        "link-global-container-height": "32px"
      }
    },
  },
};
