// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: Resizable
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "borderColor": {
        "resizable-border-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "resizable-border-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))"
      },
      "spacing": {
        "resizable-border-width": "1px"
      }
    },
  },
};
